# Generated by Django 5.2.7 on 2025-10-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Главный заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='Заказать звонок', max_length=100, verbose_name='Текст кнопки')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='3D модель')),
            ],
            options={
                'verbose_name': 'Секция Hero',
                'verbose_name_plural': 'Секции Hero',
            },
        ),
        migrations.CreateModel(
            name='HowToOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (эмодзи или HTML)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='how_to_order/', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': "Шаг 'Как заказать'",
                'verbose_name_plural': "Шаги 'Как заказать'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info/', verbose_name='Фото')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('button_text', models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(default='#', verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Секция Информация',
                'verbose_name_plural': 'Секции Информация',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Элемент прайс-листа',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('image', models.ImageField(upload_to='transport/', verbose_name='Фото транспорта')),
                ('button_text', models.CharField(default='Заказать', max_length=50, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (эмодзи)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Почему выбрать нас',
                'verbose_name_plural': 'Почему выбрать нас',
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фото работы',
            },
        ),
    ]
