# Generated by Django 5.2.7 on 2026-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Главный заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='Заказать звонок', max_length=100, verbose_name='Текст кнопки')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='3D модель')),
            ],
            options={
                'verbose_name': 'Секция Hero',
                'verbose_name_plural': 'Секции Hero',
            },
        ),
        migrations.CreateModel(
            name='HowToOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (эмодзи или HTML)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='how_to_order/', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': "Шаг 'Как заказать'",
                'verbose_name_plural': "Шаги 'Как заказать'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info/', verbose_name='Фото')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('button_text', models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Секция Информация',
                'verbose_name_plural': 'Секции Информация',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Элемент прайс-листа',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True, verbose_name='Страница')),
                ('stars', models.FloatField(default=0, verbose_name='Оценка')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
            ],
            options={
                'verbose_name': 'Рейтинг страницы',
                'verbose_name_plural': 'Рейтинги страниц',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (эмодзи)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Почему выбрать нас',
                'verbose_name_plural': 'Почему выбрать нас',
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фото работы',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='ЧПУ (например: legkovye)')),
                ('image', models.ImageField(upload_to='transport/', verbose_name='Главное фото')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='transport/icons/', verbose_name='Иконка')),
                ('button_text', models.CharField(default='Заказать эвакуатор', max_length=50, verbose_name='Текст кнопки')),
                ('price_from', models.DecimalField(decimal_places=0, default=2500, max_digits=8, verbose_name='Цена от')),
                ('features', models.TextField(blank=True, verbose_name='Особенности')),
                ('gallery', models.ManyToManyField(blank=True, related_name='transport_gallery', to='core.workphoto')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('default', 'Обычная страница'), ('metro', 'Метро'), ('district', 'Районы'), ('region', 'Области'), ('highway', 'Шоссе'), ('service', 'Услуга')], db_index=True, default='default', max_length=20, verbose_name='Тип страницы')),
                ('name', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для главной страницы', max_length=150, null=True, unique=True, verbose_name='URL страницы')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='Главная страница')),
                ('info_name', models.CharField(blank=True, max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='SEO-Ключевые слова')),
                ('fastorder', models.BooleanField(default=False, verbose_name='показать Срочный заказ эвакуатора')),
                ('calculator', models.BooleanField(default=False, verbose_name='показать калькулятор')),
                ('question_map', models.BooleanField(default=False, verbose_name='показать Остались вопросы')),
                ('map_show', models.BooleanField(default=False, verbose_name='показать картy')),
                ('payment_show', models.BooleanField(default=False, verbose_name='показать qr')),
                ('second_hero_section', models.BooleanField(default=False, verbose_name='показать второй тип hero section')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная страница')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='pages', to='core.article', verbose_name='Статьи')),
                ('faqs', models.ManyToManyField(blank=True, related_name='pages', to='core.faq', verbose_name='FAQ')),
                ('hero_sections', models.ManyToManyField(blank=True, related_name='pages', to='core.herosection', verbose_name='Hero секции')),
                ('how_to_order_steps', models.ManyToManyField(blank=True, related_name='pages', to='core.howtoorderstep', verbose_name="Шаги 'Как заказать'")),
                ('info_sections', models.ManyToManyField(blank=True, related_name='pages', to='core.infosection', verbose_name='Инфо секции')),
                ('price_items', models.ManyToManyField(blank=True, related_name='pages', to='core.priceitem', verbose_name='Прайс-лист')),
                ('ratings', models.ManyToManyField(blank=True, related_name='pages', to='core.rating', verbose_name='Рейтинги')),
                ('transport_types', models.ManyToManyField(blank=True, related_name='pages', to='core.transporttype', verbose_name='Типы транспорта')),
                ('why_choose_us', models.ManyToManyField(blank=True, related_name='pages', to='core.whychooseus', verbose_name='Почему выбрать нас')),
                ('work_photos', models.ManyToManyField(blank=True, related_name='pages', to='core.workphoto', verbose_name='Фото работ')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
