# Generated by Django 5.2.7 on 2025-10-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True, verbose_name='Страница')),
                ('stars', models.FloatField(default=0, verbose_name='Оценка')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
            ],
            options={
                'verbose_name': 'Рейтинг страницы',
                'verbose_name_plural': 'Рейтинги страниц',
            },
        ),
    ]
