# Generated by Django 5.2.7 on 2026-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, help_text='Оставьте пустым для главной страницы. Можно использовать слеши (/) для вложенных URL', max_length=150, null=True, unique=True, verbose_name='URL страницы'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
