# Generated by Django 5.2.6 on 2025-09-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calculatoroption_district_faq_formconfig_herosection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstep',
            name='icon',
            field=models.FileField(blank=True, help_text='Icon for the step', upload_to='order_icons/', verbose_name='Иконка шага'),
        ),
    ]
