# Generated by Django 5.2.7 on 2025-10-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosection',
            name='button_link',
            field=models.URLField(blank=True, default='#', verbose_name='Ссылка кнопки'),
        ),
    ]
