# Generated by Django 5.2.7 on 2026-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_page_ratings_alter_page_slug_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('default', 'Обычная страница'), ('metro', 'Метро'), ('district', 'Районы'), ('region', 'Области'), ('highway', 'Шоссе'), ('service', 'Услуга'), ('evacuator_city_mo', 'Эвакуатор по городам МО')], db_index=True, default='default', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
