# Generated by Django 5.2.7 on 2025-10-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_infosection_button_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosection',
            name='button_link',
        ),
    ]
