# Generated by Django 5.2.7 on 2026-03-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_page_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('vehicle_type', models.CharField(choices=[('evacuator', 'Эвакуатор'), ('manipulator', 'Манипулятор')], default='evacuator', max_length=20, verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга (калькулятор)',
                'verbose_name_plural': 'Дополнительные услуги (калькулятор)',
                'ordering': ['vehicle_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('vehicle_type', models.CharField(choices=[('evacuator', 'Эвакуатор'), ('manipulator', 'Манипулятор')], default='evacuator', max_length=20, verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Тип транспорта (калькулятор)',
                'verbose_name_plural': 'Типы транспорта (калькулятор)',
                'ordering': ['vehicle_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price_per_100km', models.PositiveIntegerField(default=0, verbose_name='Цена за 100 км')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.calculatorvehicletype', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Категория (калькулятор)',
                'verbose_name_plural': 'Категории (калькулятор)',
                'ordering': ['vehicle_type', 'name'],
            },
        ),
    ]
