# Generated by Django 5.2.6 on 2025-09-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderstep_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstep',
            name='number_icon',
            field=models.FileField(blank=True, help_text='Number icon for the step', upload_to='order_number_icons/', verbose_name='Номерная иконка'),
        ),
    ]
