# Generated by Django 5.2.7 on 2026-03-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calculatorextraservice_calculatorvehicletype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatorcategory',
            options={'ordering': ['vehicle_type', 'order', 'name'], 'verbose_name': 'Категория (калькулятор)', 'verbose_name_plural': 'Категории (калькулятор)'},
        ),
        migrations.AlterModelOptions(
            name='calculatorextraservice',
            options={'ordering': ['vehicle_type', 'order', 'name'], 'verbose_name': 'Дополнительная услуга (калькулятор)', 'verbose_name_plural': 'Дополнительные услуги (калькулятор)'},
        ),
        migrations.AlterModelOptions(
            name='calculatorvehicletype',
            options={'ordering': ['vehicle_type', 'order', 'name'], 'verbose_name': 'Тип транспорта (калькулятор)', 'verbose_name_plural': 'Типы транспорта (калькулятор)'},
        ),
        migrations.AddField(
            model_name='calculatorcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='calculatorextraservice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='calculatorvehicletype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
