# Generated by Django 5.2.7 on 2025-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_infosection_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Показывать'),
        ),
    ]
