# Generated by Django 5.2.7 on 2025-11-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Метро',
                'verbose_name_plural': 'Метро',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='transporttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='features',
            field=models.TextField(blank=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='transport_gallery', to='core.workphoto'),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='transport/icons/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='price_from',
            field=models.DecimalField(decimal_places=0, default=2500, max_digits=8, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='ЧПУ (например: legkovye)'),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='button_text',
            field=models.CharField(default='Заказать эвакуатор', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='image',
            field=models.ImageField(upload_to='transport/', verbose_name='Главное фото'),
        ),
    ]
