# Generated by Django 5.2.7 on 2025-11-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_metro_alter_article_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название округа')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='ЧПУ (vao)')),
                ('short_name', models.CharField(help_text='Например: ВАО, ЦАО', max_length=20, verbose_name='Короткое название')),
                ('image', models.ImageField(upload_to='districts/', verbose_name='Фото округа')),
                ('description', models.TextField(blank=True, verbose_name='Описание округа')),
                ('price_note', models.CharField(blank=True, help_text='Например: +500 ₽ за МКАД', max_length=200, verbose_name='Особенности цен')),
                ('metro_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во станций метро')),
                ('population', models.CharField(blank=True, max_length=50, verbose_name='Население')),
            ],
            options={
                'verbose_name': 'Округ Москвы',
                'verbose_name_plural': 'Округа Москвы',
                'ordering': ['name'],
            },
        ),
    ]
