# Generated by Django 5.2.7 on 2025-11-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='ЧПУ (salarevo)')),
                ('line', models.CharField(max_length=100, verbose_name='Линия метро')),
                ('line_color', models.CharField(default='#FF0000', max_length=7, verbose_name='Цвет линии (hex)')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='metro/', verbose_name='Фото станции')),
                ('description', models.TextField(blank=True, verbose_name='Описание для SEO')),
                ('price_note', models.CharField(blank=True, help_text='Например: +500 ₽ за выезд ночью', max_length=200, verbose_name='Особенность цены')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Metro',
        ),
    ]
