# Generated by Django 5.2.7 on 2025-11-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_metrostation_delete_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrostation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='line',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='line_color',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='price_note',
        ),
    ]
