# Generated by Django 5.2.7 on 2025-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_metrostation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='ЧПУ (khimki)')),
                ('info_name', models.CharField(blank=True, help_text='Например: Эвакуатор в Химках — недорого и быстро', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('info_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Фото города')),
                ('population', models.CharField(blank=True, max_length=50, verbose_name='Население')),
                ('distance_from_mkad', models.PositiveIntegerField(default=0, verbose_name='Расстояние от МКАД, км')),
            ],
            options={
                'verbose_name': 'Город МО',
                'verbose_name_plural': 'Города МО',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='district',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='description',
        ),
        migrations.AddField(
            model_name='district',
            name='info_description',
            field=models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы'),
        ),
        migrations.AddField(
            model_name='district',
            name='info_name',
            field=models.CharField(blank=True, help_text='Например: Эвакуатор в ВАО — Восточный округ Москвы', max_length=150, verbose_name='Заголовок страницы (H1)'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='info_description',
            field=models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='info_name',
            field=models.CharField(blank=True, help_text='Например: Эвакуатор у метро Саларьево — от 2500 ₽', max_length=150, verbose_name='Заголовок страницы (H1)'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='line',
            field=models.CharField(blank=True, max_length=100, verbose_name='Линия метро'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='line_color',
            field=models.CharField(blank=True, default='#FF0000', max_length=7, verbose_name='Цвет линии (hex)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='districts/', verbose_name='Фото округа'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Особенности цен'),
        ),
        migrations.AlterField(
            model_name='district',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Короткое название'),
        ),
    ]
