# Generated by Django 5.2.7 on 2025-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_city_remove_district_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruzovoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название (например: Грузовой эвакуатор до 10 тонн)')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ (gruzovoy-evakuator-do-10-tonn)')),
                ('info_name', models.CharField(blank=True, help_text='Например: Грузовой эвакуатор в Москве и области — от 8000 ₽', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('info_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gruzovoy/', verbose_name='Фото грузового эвакуатора')),
                ('price_from', models.PositiveIntegerField(default=8000, verbose_name='Цена от, руб')),
                ('weight_max', models.PositiveIntegerField(default=10, verbose_name='Макс. вес авто, тонн')),
            ],
            options={
                'verbose_name': 'Грузовой эвакуатор',
                'verbose_name_plural': 'Грузовые эвакуаторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шоссе')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='ЧПУ (dmitrovskoe-shosse)')),
                ('info_name', models.CharField(blank=True, help_text='Например: Эвакуатор по Дмитровскому шоссе — быстро и недорого', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('info_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='highways/', verbose_name='Фото шоссе')),
                ('length_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина шоссе, км')),
            ],
            options={
                'verbose_name': 'Шоссе',
                'verbose_name_plural': 'Шоссе',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manipulyator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название (например: Эвакуатор с манипулятором)')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ (manipulyator)')),
                ('info_name', models.CharField(blank=True, help_text='Например: Эвакуатор с краном-манипулятором в Москве', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('info_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='manipulyator/', verbose_name='Фото манипулятора')),
                ('price_from', models.PositiveIntegerField(default=12000, verbose_name='Цена от, руб')),
                ('arrow_length', models.CharField(blank=True, max_length=30, verbose_name='Длина стрелы')),
            ],
            options={
                'verbose_name': 'Эвакуатор-манипулятор',
                'verbose_name_plural': 'Эвакуаторы-манипуляторы',
                'ordering': ['name'],
            },
        ),
    ]
