# Generated by Django 5.2.7 on 2025-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gruzovoy_highway_manipulyator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='ЧПУ (salarevo)')),
                ('info_name', models.CharField(blank=True, help_text='Например: Эвакуатор у метро Саларьево — от 2500 ₽', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('info_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
            ],
            options={
                'verbose_name': 'Станция область',
                'verbose_name_plural': 'Станции область',
                'ordering': ['name'],
            },
        ),
    ]
