# Generated by Django 5.2.7 on 2026-01-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='distance_from_mkad',
        ),
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.RemoveField(
            model_name='district',
            name='metro_count',
        ),
        migrations.RemoveField(
            model_name='district',
            name='population',
        ),
        migrations.RemoveField(
            model_name='district',
            name='price_note',
        ),
        migrations.RemoveField(
            model_name='gruzovoy',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gruzovoy',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='gruzovoy',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='highway',
            name='image',
        ),
        migrations.RemoveField(
            model_name='highway',
            name='length_km',
        ),
        migrations.RemoveField(
            model_name='manipulyator',
            name='arrow_length',
        ),
        migrations.RemoveField(
            model_name='manipulyator',
            name='image',
        ),
        migrations.RemoveField(
            model_name='manipulyator',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='line',
        ),
        migrations.RemoveField(
            model_name='metrostation',
            name='line_color',
        ),
        migrations.AddField(
            model_name='city',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='city',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='district',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='district',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='gruzovoy',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='gruzovoy',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='highway',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='highway',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='manipulyator',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='manipulyator',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='region',
            name='page_text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='region',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='Под заголовок'),
        ),
    ]
