# Generated by Django 5.2.7 on 2026-01-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_city_distance_from_mkad_remove_city_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
        migrations.AddField(
            model_name='district',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
        migrations.AddField(
            model_name='gruzovoy',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
        migrations.AddField(
            model_name='highway',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
        migrations.AddField(
            model_name='manipulyator',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
        migrations.AddField(
            model_name='region',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста'),
        ),
    ]
