# Generated by Django 5.2.7 on 2026-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_city_page_title_district_page_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='gruzovoy',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='highway',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='manipulyator',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='metrostation',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='info_description',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='city',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
        migrations.AddField(
            model_name='district',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='district',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
        migrations.AddField(
            model_name='gruzovoy',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='gruzovoy',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
        migrations.AddField(
            model_name='highway',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='highway',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
        migrations.AddField(
            model_name='manipulyator',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='manipulyator',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Например: эвакуатор услуги, эвакуация авто москва, грузовой эвакуатор', verbose_name='SEO-Ключевые слова для детальной страницы'),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок'),
        ),
    ]
