# Generated by Django 5.2.7 on 2026-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_info_description_city_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, help_text='Например: О нашей компании — профессиональные услуги эвакуации', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('meta_keywords', models.TextField(blank=True, help_text='Например: о компании эвакуатор, история компании, наши преимущества', verbose_name='SEO-Ключевые слова для детальной страницы')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страница 'О нас'",
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, help_text='Например: Полезные статьи об услугах эвакуации', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('meta_keywords', models.TextField(blank=True, help_text='Например: статьи про эвакуацию, советы автомобилистам, полезная информация', verbose_name='SEO-Ключевые слова для детальной страницы')),
            ],
            options={
                'verbose_name': "Страница 'Статьи'",
                'verbose_name_plural': "Страница 'Статьи'",
            },
        ),
        migrations.CreateModel(
            name='CalculatorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, help_text='Например: Расчет стоимости эвакуации автомобиля', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('meta_keywords', models.TextField(blank=True, help_text='Например: калькулятор эвакуации, рассчитать стоимость, онлайн расчет', verbose_name='SEO-Ключевые слова для детальной страницы')),
            ],
            options={
                'verbose_name': "Страница 'Калькулятор'",
                'verbose_name_plural': "Страница 'Калькулятор'",
            },
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, help_text='Например: Фотогалерея наших работ и эвакуаторов', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('meta_keywords', models.TextField(blank=True, help_text='Например: фото эвакуаторов, галерея работ, наши автомобили', verbose_name='SEO-Ключевые слова для детальной страницы')),
            ],
            options={
                'verbose_name': "Страница 'Галерея'",
                'verbose_name_plural': "Страница 'Галерея'",
            },
        ),
        migrations.CreateModel(
            name='PricePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, help_text='Например: Цены на услуги эвакуатора в Москве и области', max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание для детальной страницы')),
                ('meta_keywords', models.TextField(blank=True, help_text='Например: цены на эвакуатор, стоимость услуг, прайс-лист эвакуация', verbose_name='SEO-Ключевые слова для детальной страницы')),
            ],
            options={
                'verbose_name': "Страница 'Цены'",
                'verbose_name_plural': "Страница 'Цены'",
            },
        ),
    ]
