# Generated by Django 5.2.7 on 2026-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aboutpage_articlepage_calculatorpage_gallerypage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL страницы')),
                ('info_name', models.CharField(blank=True, max_length=150, verbose_name='Заголовок страницы (H1)')),
                ('sub_description', models.TextField(blank=True, verbose_name='Под заголовок')),
                ('page_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок текста')),
                ('page_text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='SEO-Заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='SEO-Ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная страница')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='pages', to='core.article', verbose_name='Статьи')),
                ('cities', models.ManyToManyField(blank=True, related_name='pages', to='core.city', verbose_name='Города МО')),
                ('districts', models.ManyToManyField(blank=True, related_name='pages', to='core.district', verbose_name='Округа')),
                ('faqs', models.ManyToManyField(blank=True, related_name='pages', to='core.faq', verbose_name='FAQ')),
                ('gruzovoys', models.ManyToManyField(blank=True, related_name='pages', to='core.gruzovoy', verbose_name='Грузовые эвакуаторы')),
                ('hero_sections', models.ManyToManyField(blank=True, related_name='pages', to='core.herosection', verbose_name='Hero секции')),
                ('highways', models.ManyToManyField(blank=True, related_name='pages', to='core.highway', verbose_name='Шоссе')),
                ('how_to_order_steps', models.ManyToManyField(blank=True, related_name='pages', to='core.howtoorderstep', verbose_name="Шаги 'Как заказать'")),
                ('info_sections', models.ManyToManyField(blank=True, related_name='pages', to='core.infosection', verbose_name='Инфо секции')),
                ('manipulyators', models.ManyToManyField(blank=True, related_name='pages', to='core.manipulyator', verbose_name='Манипуляторы')),
                ('metro_stations', models.ManyToManyField(blank=True, related_name='pages', to='core.metrostation', verbose_name='Станции метро')),
                ('price_items', models.ManyToManyField(blank=True, related_name='pages', to='core.priceitem', verbose_name='Прайс-лист')),
                ('ratings', models.ManyToManyField(blank=True, related_name='pages', to='core.rating', verbose_name='Рейтинги')),
                ('regions', models.ManyToManyField(blank=True, related_name='pages', to='core.region', verbose_name='Области')),
                ('transport_types', models.ManyToManyField(blank=True, related_name='pages', to='core.transporttype', verbose_name='Типы транспорта')),
                ('why_choose_us', models.ManyToManyField(blank=True, related_name='pages', to='core.whychooseus', verbose_name='Почему выбрать нас')),
                ('work_photos', models.ManyToManyField(blank=True, related_name='pages', to='core.workphoto', verbose_name='Фото работ')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
