# Generated by Django 5.2.7 on 2026-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='calculator',
            field=models.BooleanField(default=False, verbose_name='показать калькулятор'),
        ),
    ]
