# Generated by Django 5.2.7 on 2026-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_page_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте пустым для главной страницы', max_length=150, null=True, unique=True, verbose_name='URL страницы'),
        ),
    ]
