# Generated by Django 5.2.7 on 2026-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_page_is_homepage_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fastorder',
            field=models.BooleanField(default=False, verbose_name='показать Срочный заказ эвакуатора'),
        ),
        migrations.AddField(
            model_name='page',
            name='map_show',
            field=models.BooleanField(default=False, verbose_name='показать картy'),
        ),
        migrations.AddField(
            model_name='page',
            name='okrug',
            field=models.BooleanField(default=False, verbose_name='показать список округов'),
        ),
        migrations.AddField(
            model_name='page',
            name='payment_show',
            field=models.BooleanField(default=False, verbose_name='показать qr'),
        ),
        migrations.AddField(
            model_name='page',
            name='question_map',
            field=models.BooleanField(default=False, verbose_name='показать Остались вопросы'),
        ),
        migrations.AddField(
            model_name='page',
            name='second_hero_section',
            field=models.BooleanField(default=False, verbose_name='показать втарох тип hero section'),
        ),
    ]
