# Generated by Django 5.2.7 on 2026-01-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_page_fastorder_page_map_show_page_okrug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='okrug',
        ),
    ]
